### DISCUSSION TITLE
Issue with pre-commit and this ruleset

### DISCUSSION THREAD

**Discussion by Cesarsk** [terraform-linters/tflint-ruleset-aws#822] [Q&A] [answered]
Hello,

I’m using the following pre-commit config file:

```
- repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
```

And the following .tflint.hcl file:

```
plugin "aws" {
  enabled = true
  version = "0.37.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

Every time I run `pre-commit run`, I encounter an error:

```
TFLint in terraform/:
Plugin “aws” SDK version (0.14.0) is incompatible. Compatible versions: >= 0.16.0
```

If I run `tflint -v`, I get the following output:

```
TFLint version 0.55.0
+ ruleset.aws (0.37.0)
+ ruleset.terraform (0.10.0-bundled)
```

For some reason, the SDK is pointing to the wrong file. If I replace the `__GIT_WORKING_DIR__` variable with the absolute file path, I still get the same error. Strangely enough, if I remove the `--args=` option, it works.

Could you please help me understand what’s causing this issue? I’m running on a Mac and using pre-commit version 4.1.0. The packages are installed using Brew.
